# Generated by Django 4.0.4 on 2022-05-22 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_alter_category_id_alter_comment_id_alter_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_title', models.CharField(max_length=50)),
                ('review_content', models.TextField(max_length=500)),
                ('review_date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.review')),
                ('review_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-review_date_posted'],
            },
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
